title: Emma Jones Resume
author: EmmaDoubleL
email: EmmaLauraPM@gmail.com
description: > project manager and operations leader # this means to ignore newlines until "baseurl:"
  documents You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # EmmaDoubleL


show_excerpts: true # set to false to remove excerpts on the homepage
